### ISSUE TITLE
The final exam papers

### ISSUE THREAD

**Issue by TIM-LIU20219** [WTW0313/EE6222#1]
Hi, could you please provide the google drive link to past years' final exam papers? It would be better if there are answers to them.
Thanks for the work you`ve done!

**Comment by WTW0313** [comment]
You can find it in the commits history.

> Hi, could you please provide the google drive link to past years' final exam papers? It would be better if there are answers to them. Thanks for the work you`ve done!

**Comment by TIM-LIU20219** [comment]
Got it, thanks!
